<link rel="stylesheet" href="<?php echo $this->base_url ?>/css/form.css" />
<link rel="stylesheet" href="<?php echo $this->base_url ?>/css/box.css" />
<link rel="stylesheet" href="<?php echo $this->base_url ?>/css/login.css" />

<div class="form box login">
	<form method="post" action="<?php echo $this->base_url ?>/">
		<div class="header">
			<h2>DoG Abimottowahl</h2>
		</div>

		<div class="notices">
			<?php foreach ($this->notices as $notice) : ?>
				<?php if ($notice == "voting_done") : ?>
					<div class="notice success">
                        投票ありがとうございます！
					</div>
				<?php endif; ?>
				<?php if ($notice == "invalid_credentials") : ?>
					<div class="notice error">
                        登録できませんでした！ ユーザー名とパスワードを確認してください！
					</div>
				<?php endif; ?>
				<?php if ($notice == "already_voted") : ?>
					<div class="notice error">
                        あなたはすでに投票しました！
					</div>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>

		<div class="content">
		  	<div class="element text">
		  		<span class="label">
		  			<label for="account_name">ユーザー名: </label>
		  		</span>
		  		<span class="control">
		  			<input type="text" name="account_name" id="account_name" autofocus="true" value="<?= escape($this->account_name) ?>" />
		  		</span>
		  	</div>

		  	<div class="element text">
		  		<span class="label">
		  			<label for="account_password">パスワード: </label>
		  		</span>
		  		<span class="control">
		  			<input type="password" name="account_password" id="account_password" />
		  		</span>
		  	</div>
		</div>

		<div class="footer">
		  	<div class="element button">
		  		<span class="control">
		  			<input type="submit" name="account_submit" value="ログイン" />
		  		</span>
		  	</div>
		</div>
	</form>
</div>
